map_type: costmap

#Obstacle marking parameters
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0


#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 0.3


#Cost function parameters
inflation_radius: 0.55
cost_scaling_factor: 10.0


#The footprint of the robot and associated padding
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
footprint_padding: 0.01


#Voxel grid specific parameters
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 9
mark_threshold: 0


#The cost at which a cell is considered an obstacle when a map is read from the map_server
lethal_cost_threshold: 100


#Configuration for the sensors that the costmap will use to update a map
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, expected_update_rate: 0.4,observation_persistence: 0.0, topic: /udacity_bot/laser/scan, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
